[project]
name = "system-setup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "ansible>=6.7.0",
]

[dependency-groups]
dev = [
    "ansible-lint>=6.8.7",
]
